### ISSUE TITLE
하단(미디어위키:ModernSidebarFooter)문서가 존재하지 않습니다.

### ISSUE THREAD

**Issue by s3ongsil** [wiki-chan/ModernSkylight#10]
위키 버전 : mediawiki-1.27.1

http://wiki-chan.github.io/ModernSkylight/

스킨 다운 받고 적용하였습니다. 위의 사이트에 나온대로 상단과 하단을 설정하려고하는데,
문서가 존재하지 않습니다.
새롭게 생성하면 될까해서 해봤는데, 문서만 생성되지 위키스킨에는 적용이 안됩니다.

상단문서는 적용이 됩니다.
하단문서가 적용이 안됩니다.

원인을 찾았네요.
문서의 내용중 `미디어위키:ModernSidebarFooter` > `미디어위키:ModernSkylightFooter` 문서를 생성하여
적용하니 되네요.

**Comment by ghost** [comment]
푸터 쪽은 설명서에 오기가 있는 것 같습니다. (
https://github.com/wiki-chan/ModernSkylight/blob/master/README.md )에 표기되어
있듯이 다음 두 문서를 사용합니다.
미디어위키:ModernSkylightMenubar ( 영어MW라면 MediaWiki:ModernSkylightMenubar )
미디어위키:ModernSkylightFooter ( 영어MW라면 MediaWiki:ModernSkylightFooter)
이렇게 문서명을 설정해도 표시되지 않는지요?


2016년 12월 2일 오후 5:57, s3ongsil <notifications@github.com>님이 작성:

**Comment by wiki-chan-server** [comment]
오타를 7391ea140ebc964c2b52f74a745618894ae49b95 에서 업데이트했습니다.
