### ISSUE TITLE
Patch for i18n/en.json

### ISSUE THREAD

**Issue by noloader** [wiki-chan/ModernSkylight#9]
This makes `Special:Version` display the skin's name as expected in English.

```
# git diff --staged
diff --git a/i18n/en.json b/i18n/en.json
new file mode 100644
index 0000000..4c619e7
--- /dev/null
+++ b/i18n/en.json
@@ -0,0 +1,7 @@
+{
+       "@metadata": {
+               "authors": ["Fenet"]
+       },
+       "skinname-modern-skylight": "Modern Skylight",
+       "modern-skylight-desc": "Modern skin for Mediawiki Engine"
+}
```

---

![mw-modern-skylight](https://cloud.githubusercontent.com/assets/3538226/19828857/b5a56678-9d9f-11e6-8993-4f0bd97fc00d.png)

**Comment by wiki-chan-server** [comment]
Thank you for contribution. Could you send us this patch using Pull Request?
